#!/bin/bash
# Opens the well hidden Adobe Creative Suite update program.
# ~IWJ

### Functions
# Are we running on Intel?
intelchk () {
        case "$OSTYPE" in
        darwin*)
                /bin/echo "Intel OSX Detected."
                ;;
        *)
                /bin/echo "ERROR: This script is for Intel Macs only."
                exit 1
                ;;
        esac
}

# Check if root user.
rootchk () {
        if [ "$(id -u)" -ne 0 ]; then
                echo "Root is needed to run this script."
                exit 1
        fi
}

intelchk
rootchk
open /Library/Application\ Support/Adobe/OOBE/PDapp/core/Adobe\ Application\ Manager.app
